name: CI / DevSecOps Demo

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # 1) Install & test
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with: { node-version: '18' }
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Run unit tests
        run: yarn test

      # 2) CodeQL analysis
      # 2) CodeQL analysis
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: javascript
      - name: Autobuild
        uses: github/codeql-action/autobuild@v2

      - name: Run CodeQL queries
        uses: github/codeql-action/analyze@v2

      # 3) Container image build & scan
      - name: Build Docker Image
        run: docker build -t demo-app:${{ github.sha }} .

      # 4) (Optional) IaC scan
      - name: Terraform fmt & validate
        run: |
          if [ -d infra ]; then
            cd infra
            terraform fmt -check
            terraform validate
          else
            echo "infra/ not found — skipping Terraform scan"
          fi
      # 5) Push artifact or deploy to staging
      - name: Publish Docker image
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: your-registry/demo-app:latest
